### ISSUE TITLE
Revue mi-projet

### ISSUE THREAD

**Issue by SpicyPaper** [HE-Arc/Wolves-Tournament-Master#29]
Vous avez mit le backend dans le frontend bizarre. La structure de votre projet est un peu étrange. Vous devriez avoir un truc du genre (attention si vous décider d'adapter faîtes attention à bien tout remettre au bon niveau pour ne pas tout péter) :
- Wolves-tournament-master
  - backend
    - api
    - blabla django
  - frontend
    - public
    - src
    - blabla vuejs
  - des trucs de git et des trucs général à votre projet

Y'a surement moyen de réécrire ça de manière plus lisible, comme suggéré [ici](https://github.com/HE-Arc/slides-devweb/wiki/%5BDjango-2020---2021%5D-Revue-de-mi-projet#ifelse-vs-ifreturn)
https://github.com/HE-Arc/Wolves-Tournament-Master/blob/cdcb151ef8e1df00eebe07300bc8f90bef54aca6/backend/api/views.py#L45-L71

Je trouve que votre fichier App.vue contient trop de chose. Vous devriez séparer cela. Créez un composant Navbar par exemple, cela permettra d'avoir uniquement le strict minimum dans App.vue comme le router-view et la structure de base.
https://github.com/HE-Arc/Wolves-Tournament-Master/blob/cdcb151ef8e1df00eebe07300bc8f90bef54aca6/src/App.vue#L1

De manière générale votre logique ne devrait pas se trouver dans vos composants/views vue, vous devriez utiliser un peu plus VueX store et éventuellement créer des store si vous avez beaucoup de logique. Actuellement vos composants/views sont vraiment trop lourd.

WOW ! Ca c'est interdit ! Ne faîtes pas ça !
De l'HTML dans du JS... BEURK...
Vous utilisez VueJS qui est un framework frontend puissant et vous ne l'utilisez pas quoi... Non mais ça c'est vraiment non. Vous pouvez utiliser les v-if, v-for et autres directives fournies par VueJS. Et découper vos pages en composants vous en ressentez le besoin, mais là vous pouvez pas laissez cela comme ça. Contactez moi pour qu'on en discute si vous avez envie, mais svp laissez pas ce genre d'abomination x)
Je dit ça un peu sur le ton de la blague, mais sérieux c'est une ultra mauvaise pratique et à faire uniquement en DERNIER DERNIER DERNIIIIIIIIIIIIIIER (dernier) recours.

Je trouve votre manière d’indenter certaines choses vraiment bizarre... et ce n'est qu'un exemple parmi beaucoup d'autres...
https://github.com/HE-Arc/Wolves-Tournament-Master/blob/cdcb151ef8e1df00eebe07300bc8f90bef54aca6/src/views/Tournament.vue#L144-L148

Mettez des try/catch autour de vos async/await comme [ici](https://github.com/HE-Arc/slides-devweb/wiki/%5BDjango-2020---2021%5D-Revue-de-mi-projet#asyncawait-et-trycatch)
https://github.com/HE-Arc/Wolves-Tournament-Master/blob/cdcb151ef8e1df00eebe07300bc8f90bef54aca6/src/views/Teams.vue#L96-L103

Vous avez beaucoup de code, c'est très bien. Mais attention à la qualité de votre code aussi, vous négligez un peu trop certains aspects.

**Comment by Alan-Chambaz** [comment]
Seul l'arborescence reste inchangée. 
=> Cela nous permettra de ne rien modifier lors des futurs déploiements.

**Comment by SpicyPaper** [comment]
Si vous avez appliqué le reste (surtout l'HTML dans le JS) c'est déjà pas mal.
Expliquez et justifiez vos choix architecturaux (wiki, autre) - à un endroit que l'on peut facilement retrouver. Mais ne laissez pas ça comme ça sans en expliquer la raison.

**Comment by Alan-Chambaz** [comment]
L'arborescence a été mise à jour. 
Le frontend est maintenant dans un dossier séparé.
